### 1. How to Creating a 3x3 Identity Matrix with Float Data Type? 


In [2]:
import numpy as np
matrix = np.identity(3, dtype=float)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2. Create a 1D Array with Random Values between 0 and 1. 


In [27]:
array1 = np.random.rand(4)
array1

array([0.34872763, 0.17149121, 0.7218703 , 0.58779042])

### 3. Create a 2D Array with Random Integer Values. 

In [30]:
array2 = np.random.randint(0, 20, (3, 4))
array2

array([[ 1,  9,  5, 11],
       [16,  1, 10,  1],
       [ 2,  4,  6,  6]])

### 4. Creating an Array Using a Custom Function.

In [15]:
def cf(i, j):
    return np.random.randint(i, j,(4, 4))

cf(20, 40)

array([[20, 32, 31, 36],
       [22, 38, 26, 32],
       [25, 32, 34, 38],
       [36, 39, 20, 32]])

### 5. Reshaping a 1D Array into a 2D Array 

In [2]:
a = np.array([1,2,3,4,5,6,7,8])
b =a.reshape(2, 4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 6.How to Creating a 3x3 Array of Ones?

In [22]:
aones = np.ones((3, 3))
aones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 7. How to get the common items between two pythons NumPy? 

In [27]:
a = np. array ([1,2,3,2,3,4,3,4,5,6]) 
b = np. array ([7,2,10,2,7,4,9,4,9,8]) 
c = np.intersect1d(a, b)
c

array([2, 4])

### 8. From array a remove all items present in array b 

In [32]:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9]) 

c = np.setdiff1d(a, b)
c

array([1, 2, 3, 4])

### 9. Limit the number of items printed in python NumPy array a to a maximum of 6 elements. 

In [36]:
a = np.arange(15) 
np.set_printoptions()
a

array([ 0,  1,  2, ..., 12, 13, 14])

### 10. Drop all nan values from a 1D NumPy 


In [42]:
a = np. array ([1,2,3, np.nan,5,6,7, np.nan]) 
b = a[~np.isnan(a)]
b

array([1., 2., 3., 5., 6., 7.])

### 11. Question: Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20

In [51]:
a = np.arange(1, 21)
print(a)
b = a.reshape(4, 5)
b

[ 1  2  3 ... 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### 12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. Change its data type to float64 and verify the change. 

In [3]:
array_3d = np.arange(24).reshape(2, 3, 4)

shape = array_3d.shape
size = array_3d.size
ndim = array_3d.ndim
dtype = array_3d.dtype

print("Original Array:")
print("Shape:", shape)
print("Size:", size)
print("Number of dimensions:", ndim)
print("Data type:", dtype)

array_3d_float = array_3d.astype(np.float64)
print("\nArray after changing data type to float64:")
print("Shape:", array_3d_float.shape)
print("Size:", array_3d_float.size)
print("Number of dimensions:", array_3d_float.ndim)
print("Data type:", array_3d_float.dtype)
print("Array contents:")
print(array_3d_float)

Original Array:
Shape: (2, 3, 4)
Size: 24
Number of dimensions: 3
Data type: int32

Array after changing data type to float64:
Shape: (2, 3, 4)
Size: 24
Number of dimensions: 3
Data type: float64
Array contents:
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


### 13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that the flattened array matches the original. 


In [4]:
original_array = np.arange(12)
reshaped_array = original_array.reshape(3, 4)
flattened_array = reshaped_array.ravel()

print("Original 1D Array:")
print(original_array)

print("\nReshaped 3x4 2D Array:")
print(reshaped_array)

print("\nFlattened 1D Array after ravel():")
print(flattened_array)

Original 1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 3x4 2D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened 1D Array after ravel():
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### 14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and division. Explain the behavior when dividing by zero. 

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b

print("Addition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nMultiplication:")
print(multiplication)

print("\nDivision:")
print(division)

c = np.array([1, 2, 0])
d = np.array([4, 5, 6])
division_with_zero = c / d

print("\nDivision with Zero in Numerator:")
print(division_with_zero)


Addition:
[5 7 9]

Subtraction:
[-3 -3 -3]

Multiplication:
[ 4 10 18]

Division:
[0.25 0.4  0.5 ]

Division with Zero in Numerator:
[0.25 0.4  0.  ]


### 15. Question: Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. Explain how broadcasting rules apply in this scenario. 

In [6]:
array_2d = np.array([[1], [2], [3]])
array_1d = np.array([10, 20, 30])
result = array_2d + array_1d

print("2D Array (shape (3, 1)):")
print(array_2d)

print("\n1D Array (length 3):")
print(array_1d)

print("\nResult of addition:")
print(result)

2D Array (shape (3, 1)):
[[1]
 [2]
 [3]]

1D Array (length 3):
[10 20 30]

Result of addition:
[[11 21 31]
 [12 22 32]
 [13 23 33]]


### 16. Question: Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5. 



In [7]:
array_2d = np.random.randint(0, 11, size=(4, 5))

print("Original 2D Array:")
print(array_2d)

mask = array_2d > 5

print("\nBoolean Mask (elements > 5):")
print(mask)

array_2d[mask] = 5

print("\nModified 2D Array (elements > 5 replaced with 5):")
print(array_2d)

Original 2D Array:
[[ 7  0  1  4 10]
 [ 8  0  2  3  5]
 [ 8  2  3  1  2]
 [ 8  4  9  5  4]]

Boolean Mask (elements > 5):
[[ True False False False  True]
 [ True False False False False]
 [ True False False False False]
 [ True False  True False False]]

Modified 2D Array (elements > 5 replaced with 5):
[[5 0 1 4 5]
 [5 0 2 3 5]
 [5 2 3 1 2]
 [5 4 5 5 4]]


### 17. Question: Given a 4x4 array of random integers, use indexing and slicing to extract: 
* o The entire second row 
* o The last column 
* o The subarray consisting of the first two rows and first two columns

In [22]:
array_4 = np.random.randint(0,20, (4,4))
print(array_4)
print(array_4[1,:])
print(array_4[:,-1])
print(array_4[:2,:2])

[[ 2  7 12  6]
 [13  4  1  5]
 [10 19 15  5]
 [19 14 10  5]]
[13  4  1  5]
[6 5 5 5]
[[ 2  7]
 [13  4]]


### 18. Question: Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution for a simple task in each area. 

In [23]:
#1 EDA

data = np.array([12, 15, 14, 10, 18, 21, 14, 13, 16, 19])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

#2 AI

data = np.array([[100, 2000, 3], [200, 4000, 6], [300, 6000, 9]])
min_vals = np.min(data, axis=0)
max_vals = np.max(data, axis=0)
normalized_data = (data - min_vals) / (max_vals - min_vals)

print("Normalized Data:")
print(normalized_data)

#3 ML

X = np.array([[1], [2], [3], [4]])
X_poly = np.hstack([X, X**2])

print("Original Features:")
print(X)
print("Polynomial Features:")
print(X_poly)

#4 DL

data = np.random.randn(10, 4)
batch_size = 3
num_batches = data.shape[0] // batch_size
batches = np.array_split(data, num_batches)

print("Data Batches:")
for i, batch in enumerate(batches):
    print(f"Batch {i + 1}:")
    print(batch)


Mean: 15.2
Median: 14.5
Standard Deviation: 3.1874754901018454
Normalized Data:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
Original Features:
[[1]
 [2]
 [3]
 [4]]
Polynomial Features:
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]
Data Batches:
Batch 1:
[[-0.81277767 -1.09859372 -1.88393186  0.75712965]
 [-0.17276599 -1.08465118  0.49118843 -2.39192919]
 [-0.98890074 -0.26585602 -1.218138   -0.61046728]
 [-1.19365573 -0.12157301 -1.14942517  1.11066319]]
Batch 2:
[[ 1.14916456 -0.64729216 -0.18170634  1.1122057 ]
 [ 1.38776338 -0.07312047 -0.8652107  -0.75873818]
 [ 1.64680987  0.54819958  0.48059213  0.46987342]]
Batch 3:
[[-1.60461311 -1.88315248 -0.21531378  0.16390877]
 [-0.32265482 -0.50961037  0.36917971  0.69568781]
 [ 1.36364822 -0.19022546 -0.29236223 -1.65131074]]


### 19. Question: Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix. 


In [26]:
matrix = np.random.rand(4, 4)

print("Original 4x4 Matrix:")
print(matrix)

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

eigenvalues_diag = np.diag(eigenvalues)
reconstructed_matrix = eigenvectors @ eigenvalues_diag @ np.linalg.inv(eigenvectors)

print("\nReconstructed Matrix:")
print(reconstructed_matrix)

print("\nMatrix reconstruction is correct:", np.allclose(matrix, reconstructed_matrix))


Original 4x4 Matrix:
[[0.21810163 0.96495265 0.40672733 0.17777791]
 [0.97156802 0.12114396 0.58751556 0.92403409]
 [0.42217011 0.19292471 0.01208008 0.97450878]
 [0.19043054 0.07246912 0.94512949 0.38800849]]

Eigenvalues:
[ 1.80771229  0.46747565 -0.90211639 -0.63373741]

Eigenvectors:
[[ 0.53603977  0.74579527  0.61677127 -0.63537075]
 [ 0.64842543  0.37847403 -0.57282237  0.62171437]
 [ 0.39561344 -0.22145417 -0.4618887  -0.29678135]
 [ 0.36836915 -0.50150262  0.2795113   0.34884965]]

Reconstructed Matrix:
[[0.21810163 0.96495265 0.40672733 0.17777791]
 [0.97156802 0.12114396 0.58751556 0.92403409]
 [0.42217011 0.19292471 0.01208008 0.97450878]
 [0.19043054 0.07246912 0.94512949 0.38800849]]

Matrix reconstruction is correct: True


### 20. Question: Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array with the original. 


In [27]:
array_1d = np.arange(27)
print(array_1d)
array_3d = array_1d.reshape((3, 3, 3))

print("3D Array:")
print(array_3d)

flattened_array = array_3d.ravel()

print("\nFlattened 1D Array:")
print(flattened_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
3D Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Flattened 1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


### 21. Question: Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a large dataset. 

In [31]:


# Create two large random 2D arrays (1000 x 1000)
A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

# Matrix multiplication using np.dot()
result_dot = np.dot(A, B)

# Matrix multiplication using @ operator
result_at = A @ B

# Compare results to ensure they are the same
comparison = np.allclose(result_dot, result_at)

print("Results are the same:", comparison)


Results are the same: True


### 22. Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting and explain the result. Use np. new axis to achieve the same result without broadcasting. 


In [35]:
import numpy as np

# Create a 3D array of shape (2, 1, 4)
array_3d = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]])

# Create a 2D array of shape (4, 1)
array_2d = np.array([[10], [20], [30], [40]])

# Perform element-wise addition using broadcasting
result_broadcasting = array_3d + array_2d.T

print("Array 3D:")
print(array_3d)
print("\nArray 2D:")
print(array_2d)
print("\nResult using broadcasting (element-wise addition):")
print(result_broadcasting)


Array 3D:
[[[1 2 3 4]]

 [[5 6 7 8]]]

Array 2D:
[[10]
 [20]
 [30]
 [40]]

Result using broadcasting (element-wise addition):
[[[11 22 33 44]]

 [[15 26 37 48]]]


### 23. Question: Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. Replace these values with their squares and leave the rest unchanged. 

In [36]:
array = np.random.rand(5, 5)

print("Original Array:\n", array)
mask = array < 0.5
array[mask] = array[mask] ** 2

print("Modified Array:\n", array)


Original Array:
 [[0.64525384 0.30517344 0.29559523 0.24905865 0.80635255]
 [0.53927796 0.66198999 0.29248204 0.42010517 0.01443404]
 [0.75043689 0.16332292 0.54638538 0.82015582 0.89501692]
 [0.81207229 0.71297517 0.11304519 0.13757219 0.25043927]
 [0.43853756 0.66711182 0.10047763 0.96320424 0.26512703]]
Modified Array:
 [[6.45253840e-01 9.31308257e-02 8.73765373e-02 6.20302105e-02
  8.06352549e-01]
 [5.39277957e-01 6.61989994e-01 8.55457452e-02 1.76488352e-01
  2.08341431e-04]
 [7.50436890e-01 2.66743749e-02 5.46385377e-01 8.20155823e-01
  8.95016922e-01]
 [8.12072290e-01 7.12975167e-01 1.27792140e-02 1.89261070e-02
  6.27198258e-02]
 [1.92315187e-01 6.67111822e-01 1.00957548e-02 9.63204238e-01
  7.02923399e-02]]


### 24. Question: Given a 5x5 array of sequential integers, use slicing to: 
* o Extract the diagonal elements 
* o Replace the elements of the middle row with zeros 
* o Flip the array vertically and horizontally 

In [37]:
array = np.arange(25).reshape(5, 5)
print("Original Array:\n", array)

diagonal_elements = np.diagonal(array)
print("Diagonal Elements:\n", diagonal_elements)

array[2, :] = 0
print("Array with Middle Row Zeros:\n", array)

flipped_array = array[::-1, ::-1]
print("Flipped Array:\n", flipped_array)

Original Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Diagonal Elements:
 [ 0  6 12 18 24]
Array with Middle Row Zeros:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Flipped Array:
 [[24 23 22 21 20]
 [19 18 17 16 15]
 [ 0  0  0  0  0]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


### 25. Question: Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a specified axis.

In [38]:
array_4d = np.random.randint(0, 10, size=(2, 3, 4, 5))
print("Original 4D Array:\n", array_4d)

subarray = array_4d[0, 1:3, :, :]
print("Extracted Subarray:\n", subarray)

mean_along_axis2 = np.mean(subarray, axis=2)
print("Mean Along Axis 2:\n", mean_along_axis2)

Original 4D Array:
 [[[[6 1 3 7 0]
   [6 7 6 4 9]
   [4 8 2 0 9]
   [7 7 8 3 3]]

  [[6 9 6 9 5]
   [8 3 3 9 6]
   [1 3 7 8 7]
   [2 8 3 2 9]]

  [[4 0 4 8 3]
   [0 8 8 1 6]
   [3 1 4 9 1]
   [8 2 3 7 3]]]


 [[[0 5 4 6 9]
   [1 7 1 7 2]
   [4 7 4 9 2]
   [5 8 0 1 7]]

  [[2 8 8 5 3]
   [9 2 3 1 5]
   [6 2 8 5 1]
   [4 3 5 6 5]]

  [[7 9 0 4 4]
   [9 8 1 1 9]
   [3 5 0 7 3]
   [5 9 0 1 5]]]]
Extracted Subarray:
 [[[6 9 6 9 5]
  [8 3 3 9 6]
  [1 3 7 8 7]
  [2 8 3 2 9]]

 [[4 0 4 8 3]
  [0 8 8 1 6]
  [3 1 4 9 1]
  [8 2 3 7 3]]]
Mean Along Axis 2:
 [[7.  5.8 5.2 4.8]
 [3.8 4.6 3.6 4.6]]


### 26. Question: Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality. 

In [41]:
array = np.arange(200).reshape(10, 20)
print(array)

# Reshape to (20, 10)
reshaped_array_1 = array.reshape(20, 10)

print("Reshaped Array (20, 10):\n", reshaped_array_1)
print("Shape:", reshaped_array_1.shape)
print("Size:", reshaped_array_1.size)
print("Dimensionality:", reshaped_array_1.ndim)

# Reshape to (5, 40)
reshaped_array_2 = array.reshape(5, 40)

print("Reshaped Array (5, 40):\n", reshaped_array_2)
print("Shape:", reshaped_array_2.shape)
print("Size:", reshaped_array_2.size)
print("Dimensionality:", reshaped_array_2.ndim)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]
Reshaped Array (20, 10):
 [[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28

### 27. Question: Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra operations. 

In [42]:
rows, cols = 1000, 1000
large_array = np.arange(rows * cols).reshape(rows, cols)

print("Original 2D Array Shape:", large_array.shape)

reshaped_array_1 = large_array.reshape((2000, 500))
reshaped_array_2 = large_array.reshape((10, 100, 1000))

print("Reshaped Array (2000, 500):", reshaped_array_1.shape)
print("Reshaped Array (10, 100, 1000):", reshaped_array_2.shape)

flattened_array = large_array.ravel()
print("Flattened Array Shape:", flattened_array.shape)

restored_array = flattened_array.reshape(rows, cols)
print("Restored Array Shape:", restored_array.shape)

matrix_1 = np.random.rand(500, 1000)
matrix_2 = np.random.rand(1000, 500)

reshaped_matrix_1 = matrix_1.reshape(1000, 500)
reshaped_matrix_2 = matrix_2.reshape(500, 1000)

result_matrix = np.dot(reshaped_matrix_1, reshaped_matrix_2)

print("Result Matrix Shape:", result_matrix.shape)


Original 2D Array Shape: (1000, 1000)
Reshaped Array (2000, 500): (2000, 500)
Reshaped Array (10, 100, 1000): (10, 100, 1000)
Flattened Array Shape: (1000000,)
Restored Array Shape: (1000, 1000)
Result Matrix Shape: (1000, 1000)


### 28. Question: Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero. Verify the result. 


In [43]:
matrix = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Matrix:\n", matrix)

upper_triangular = np.triu(matrix)
print("Upper Triangular Part:\n", upper_triangular)

lower_triangular_zeroed = np.triu(matrix)
print("Matrix with Lower Triangular Part Set to Zero:\n", lower_triangular_zeroed)

lower_triangular_zeroed_manual = matrix.copy()
lower_triangular_zeroed_manual[np.tril_indices_from(lower_triangular_zeroed_manual, -1)] = 0
print("Manually Zeroed Lower Triangular Part Matrix:\n", lower_triangular_zeroed_manual)

print("Verification (Are the matrices equal?):", np.array_equal(lower_triangular_zeroed, lower_triangular_zeroed_manual))

Original 6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Upper Triangular Part:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Matrix with Lower Triangular Part Set to Zero:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Manually Zeroed Lower Triangular Part Matrix:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Verification (Are the matrices equal?): True
